
CREATE DATABASE VALORANT_DB;
CREATE SCHEMA VALORANT_DB.PUBLIC;
CREATE TABLE VALORANT_DB.PUBLIC.valorant_players (
    Player_Name VARCHAR,
    Team VARCHAR,
    Rating FLOAT,
    Region VARCHAR,
    Agent VARCHAR,
    Player_Category VARCHAR,
    Average_combat_score FLOAT,
    Kill_deaths FLOAT,
    Kill_assists_survived_traded FLOAT,
    Average_damage_per_round FLOAT,
    Kills_per_round FLOAT,
    Assists_per_round FLOAT,
    First_kills_per_round FLOAT,
    First_deaths_per_round FLOAT,
    Headshot_percentage FLOAT,
    Clutch_success_percentage FLOAT
);

SHOW TABLES IN VALORANT_DB.PUBLIC;

DESC TABLE VALORANT_DB.PUBLIC.VALORANT_PLAYERS;

SELECT COUNT(*) AS total_records 
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS;

SELECT * 
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
LIMIT 10;


-- Top 20 players by Rating
SELECT 
    PLAYER_NAME, 
    TEAM, 
    RATING, 
    REGION, 
    KILL_DEATHS, 
    AVERAGE_COMBAT_SCORE
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
ORDER BY RATING DESC
LIMIT 20;

-- Average Rating By Reagion
SELECT 
    REGION,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(AVERAGE_COMBAT_SCORE), 2) AS AVG_COMBAT_SCORE,
    ROUND(AVG(AVERAGE_DAMAGE_PER_ROUND), 2) AS AVG_DAMAGE
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
GROUP BY REGION
ORDER BY AVG_RATING DESC;

-- Top 25 Teams By Average Rating
SELECT 
    TEAM,
    COUNT(*) AS PLAYER_COUNT,
    ROUND(AVG(RATING), 2) AS TEAM_AVG_RATING,
    ROUND(AVG(KILL_DEATHS), 2) AS TEAM_AVG_KD,
    ROUND(AVG(HEADSHOT_PERCENTAGE), 3) AS TEAM_HEADSHOT_AVG
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
GROUP BY TEAM
HAVING COUNT(*) >= 2
ORDER BY TEAM_AVG_RATING DESC
LIMIT 25;

-- Agent Popularity And Performance
SELECT 
    AGENT,
    COUNT(*) AS PLAYER_COUNT,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(KILL_DEATHS), 2) AS AVG_KD_RATIO
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
GROUP BY AGENT
ORDER BY PLAYER_COUNT DESC;

-- Elite Players 
SELECT 
    PLAYER_NAME, 
    TEAM, 
    REGION, 
    RATING, 
    ROUND(KILL_DEATHS, 2) AS KD, 
    ROUND(HEADSHOT_PERCENTAGE, 2) AS HS_PERCENT,
    ROUND(CLUTCH_SUCCESS_PERCENTAGE, 2) AS CLUTCH_SUCCESS
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
WHERE RATING >= 1.2
ORDER BY RATING DESC;

-- Accuracey Analysis
SELECT 
    PLAYER_NAME, 
    TEAM, 
    ROUND(HEADSHOT_PERCENTAGE, 3) AS HEADSHOT_PERCENT,
    ROUND(AVERAGE_COMBAT_SCORE, 2) AS COMBAT_SCORE,
    ROUND(AVERAGE_DAMAGE_PER_ROUND, 2) AS DAMAGE
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
WHERE HEADSHOT_PERCENTAGE > 0.35
ORDER BY HEADSHOT_PERCENT DESC
LIMIT 20;

-- Entry Fraggers
SELECT 
    PLAYER_NAME,
    TEAM,
    REGION,
    ROUND(FIRST_KILLS_PER_ROUND, 2) AS FIRST_KILL_RATE,
    ROUND(FIRST_DEATHS_PER_ROUND, 2) AS FIRST_DEATH_RATE,
    RATING
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
WHERE FIRST_KILLS_PER_ROUND > FIRST_DEATHS_PER_ROUND
ORDER BY FIRST_KILL_RATE DESC
LIMIT 15;

-- Clutch Master
SELECT 
    PLAYER_NAME,
    TEAM,
    ROUND(CLUTCH_SUCCESS_PERCENTAGE, 2) AS CLUTCH_WIN_RATE,
    RATING,
    ROUND(KILL_DEATHS, 2) AS KD_RATIO
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
ORDER BY CLUTCH_WIN_RATE DESC
LIMIT 15;

-- Regionwise Damage Efficiency
SELECT 
    REGION,
    ROUND(AVG(AVERAGE_DAMAGE_PER_ROUND), 2) AS AVG_DAMAGE,
    ROUND(AVG(RATING), 2) AS AVG_RATING,
    ROUND(AVG(KILL_DEATHS), 2) AS AVG_KD
FROM VALORANT_DB.PUBLIC.VALORANT_PLAYERS
GROUP BY REGION
ORDER BY AVG_DAMAGE DESC;










